> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [3]:
!pip install jovian --upgrade -q

In [4]:
import jovian

In [5]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Updating notebook "amartyasantra07/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/amartyasantra07/numpy-array-operations


'https://jovian.com/amartyasantra07/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [6]:
import numpy as np

In [18]:
# List of functions explained 
function1 = np.repeat 
function2 = np.transpose
function3 = np.reshape
function4 = np.sin
function5 = np.around

## Function 1 - np.concatenate (change this)

Add some explanation about the function in your own words

In [19]:
# Example 1 - working (change this)
np.repeat(3,5, axis = 0)




array([3, 3, 3, 3, 3])

Explanation about example

In [20]:
# Example 2 - working


arr1 = np.array([[1,2,3],
                [3,4,5],
                [5,6,7]])
arr1

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

Explanation about example

In [21]:
arr1.shape

(3, 3)

In [22]:
arr_default = np.repeat(arr1,2)
arr_default

array([1, 1, 2, 2, 3, 3, 3, 3, 4, 4, 5, 5, 5, 5, 6, 6, 7, 7])

In [23]:
arr2 = np.repeat(arr1,3,axis=0)
arr2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [3, 4, 5],
       [3, 4, 5],
       [3, 4, 5],
       [5, 6, 7],
       [5, 6, 7],
       [5, 6, 7]])

In [24]:
arr3 = np.repeat(arr1,2,axis = 1)
arr3

array([[1, 1, 2, 2, 3, 3],
       [3, 3, 4, 4, 5, 5],
       [5, 5, 6, 6, 7, 7]])

In [25]:
arr3 = np.repeat(arr1,2,axis = 2)
arr3

AxisError: axis 2 is out of bounds for array of dimension 2

In [ ]:
#Here as we know in the array was upto axis 1, therefore it is out of bound and resulted in error. 
#Hence always check your axis and add according to it.

#In summary, np.repeat() is a useful Numpy function that allows us to repeat elements of an array along a specified axis.
#We can use it to create arrays with repeated elements, to expand arrays to match other arrays, or to add new elements to arrays.
# It provides a flexible and efficient way of manipulating arrays, and is an essential tool for many data analysis tasks.

Here as we know in the array was upto axis 1, therefore it is out of bound and resulted in error. Hence always check your axis and add according to it.

In summary, np.repeat() is a useful numpy function that allows us to repeat elements of an array along a specified axis. We can use it to create arrays with repeated elements, to expand arrays to match other arrays, or to add new elements to arrays. It provides a flexible and efficient way of manipulating arrays, and is an essential tool for many data analysis tasks.

In [23]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 2 - ???

Add some explanations

In [29]:
# Example 1 - working
y = np.array([[3, 2, 7], [9, 2, 1]])
y
np.transpose(y)

array([[3, 9],
       [2, 2],
       [7, 1]])

Explanation about example

In [30]:
# Example 2 - working
x = np.array([[[3, 2], [5, 7], [4, 6]]])
print('shape from original vector: {}'.format(x.shape))
y = np.transpose(x, (1, 2, 0))
print('shape from transposed vector: {}'.format(y.shape))
y

shape from original vector: (1, 3, 2)
shape from transposed vector: (3, 2, 1)


array([[[3],
        [2]],

       [[5],
        [7]],

       [[4],
        [6]]])

Explanation about example

In [31]:
# Example 3 - breaking (to illustrate when it breaks)
x = np.array([[[3, 2], [5, 7], [4, 6]]])
print('shape from original vector: {}'.format(x.shape))

y = np.transpose(x, (1, 2, 0, 3))
print('shape from transposed vector: {}'.format(y.shape))

shape from original vector: (1, 3, 2)


ValueError: axes don't match array

When you use the second argument, you have to be sure to use the right number of axes, otherwise, it will crash.

You can use this function when you want to get the transpose from an array (e.g. when you work with linear regression).

In [32]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "amartyasantra07/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/amartyasantra07/numpy-array-operations


'https://jovian.com/amartyasantra07/numpy-array-operations'

## Function 3 - ???

Add some explanations

In [34]:
# Example 1 - working
a = np.array([[1,2,3], [1,2,3]])
np.reshape(a, 6)

array([1, 2, 3, 1, 2, 3])

Explanation about example

In [37]:
# Example 2 - working
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a, 6, order='F')

array([1, 4, 2, 5, 3, 6])

Explanation about example

In [38]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a, 6, order='G')

ValueError: order must be one of 'C', 'F', 'A', or 'K' (got 'G')

When you use the order parameter, make sure to set a valid argument (‘C’, ‘F’ or ‘A’).

In this case, we used an invalid value ‘G’, that’s why it crashed.

You can use this function when you want to reshape an array to make it compatible with other arrays for arithmetic operations.

In [39]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "amartyasantra07/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/amartyasantra07/numpy-array-operations


'https://jovian.com/amartyasantra07/numpy-array-operations'

## Function 4 - ???

Add some explanations

In [40]:
# Example 1 - working
np.sin(np.pi/2.)

1.0

Explanation about example

In [41]:
# Example 2 - working
np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180. )

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

Explanation about example

In [42]:
# Example 3 - breaking (to illustrate when it breaks)
np.sin('5')

TypeError: ufunc 'sin' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In this case, we are getting an error due to the data type of the argument. Always use numeric values.

The sine is one of the fundamental functions of trigonometry, so you might need to use this function often.

Some closing comments about when to use this function.

In [43]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "amartyasantra07/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/amartyasantra07/numpy-array-operations


'https://jovian.com/amartyasantra07/numpy-array-operations'

## Function 5 - ???

Add some explanations

In [44]:
# Example 1 - working
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Explanation about example

In [45]:
# Example 2 - working
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6], 
        [8, 9]]

np.concatenate((arr1, arr2), axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 8., 9.]])

Explanation about example

In [46]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2], 
        [3, 4.]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

 we could either add another column to arr1 to match the number of columns in arr2, or we could concatenate them along axis 1 (horizontally) instead.

Some closing comments about when to use this function.

In [47]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "amartyasantra07/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/amartyasantra07/numpy-array-operations


'https://jovian.com/amartyasantra07/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [48]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "amartyasantra07/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/amartyasantra07/numpy-array-operations


'https://jovian.com/amartyasantra07/numpy-array-operations'