In [3]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]
w1, w2, w3 = 0.3, 0.2, 0.5

In [4]:
weights = [w1, w2, w3]

In [5]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [6]:
crop_yield(kanto, weights)

56.8

In [8]:
import numpy as np
kanto = np.array([73,67,43])


In [9]:
kanto

array([73, 67, 43])

In [10]:
weights = np.array([w1, w2, w3])

In [11]:
type(kanto)


numpy.ndarray

In [12]:
type(weights)

numpy.ndarray

In [15]:
# just like lists ,Numpy arrays support the indexing notation[]
weights[1]

0.2

In [17]:
kanto[2]

43

In [19]:
# we can now compute the dot product of the two vectors using the np.dot function 

np.dot(kanto,weights)

56.8

In [21]:
#We can achieve the same result with low-level operations supported by Numpy arrays: performing an element-wise multiplication 
#and calculating the resulting numbers' sum

(kanto * weights).sum()

56.8

In [22]:
#The * operator performs an element-wise multiplication of two arrays if they have the same size. 
#The sum method calculates the sum of numbers in an array.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [23]:
arr1 * arr2

array([ 4, 10, 18])

In [24]:
arr2.sum()

15

In [29]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [30]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

Wall time: 169 ms


833332333333500000

In [31]:
%%time
np.dot(arr1_np, arr2_np)

Wall time: 1.01 ms


-1942957984

In [32]:
#Multi-dimensional Numpy arrays

climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [33]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [34]:
climate_data.shape 
#2D array matrix

(5, 3)

In [35]:
weights

array([0.3, 0.2, 0.5])

In [36]:
weights.shape

(3,)

In [37]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

In [38]:
arr3.shape

(2, 2, 3)

In [39]:
climate_data.dtype

dtype('int32')

In [40]:
#If an array contains even a single floating point number, all the other elements are also converted to floats.
arr3.dtype

dtype('float64')

In [42]:
#We can use the np.matmul function or the @ operator to perform matrix multiplication.

np.matmul(climate_data , weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [43]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [44]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x24bba8efa90>)

In [45]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [46]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [47]:
climate_data.shape

(10000, 3)

In [48]:
weights = np.array([0.3, 0.2, 0.5])

In [49]:
yields = climate_data @ weights

In [50]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [51]:
yields.shape

(10000,)